### ISSUE TITLE
can't compile project

### ISSUE THREAD

**Issue by Manuelmik** [Ahmedazim7804/flutter_bar_hyprland#1]
Hello, when i try to compile the project i get  the following error: 
_"ERROR: ../../.pub-cache/hosted/pub.dev/fading_edge_scrollview-3.0.0/lib/src/fading_edge_scrollview.dart:116:32: Error: The argument type 'PageController?' can't be assigned to the parameter type 'ScrollController' because 'PageController?' is nullable and 'ScrollController' isn't."_
The marquee package depends on the fading_edge_scrollview package
I fixed it by adding the following to pubspec.yaml
```
dependency_overrides:
   fading_edge_scrollview: ^4.1.1

```
It compiles but now I get this error (presumably from GTK) 
_"** (bar:24828): CRITICAL **: 08:28:26.770: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (bar:24828): CRITICAL **: 08:28:26.770: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (bar:24828): CRITICAL **: 08:28:26.770: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(bar:24828): GLib-GObject-CRITICAL **: 08:28:26.770: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (bar:24828): CRITICAL **: 08:28:26.770: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (bar:24828): CRITICAL **: 08:28:26.770: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (bar:24828): CRITICAL **: 08:28:26.770: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed"_

Thanks in advance!

**Comment by Ahmedazim7804** [comment]
can you try now, i have replaced "Marquee" package.
also you might get some error related to workspace if you are on latest version of hyprland, ignore them for now they are harmless. i will update it for latest version soon.

**Comment by Manuelmik** [comment]
ignoring the error message doesn't help because I can't see the application or in other words nothing gets displayed.

**Comment by Ahmedazim7804** [comment]
alright, i will check it. meanwhile i can include the binary if you want.

**Comment by Manuelmik** [comment]
thank you i can try it out and see if that works.

**Comment by Ahmedazim7804** [comment]
I have uploaded the binaries in [release](https://github.com/Ahmedazim7804/flutter_bar_hyprland/releases/tag/v1.0.0) section. Also keep the other folders along the binary file.

**Comment by Manuelmik** [comment]
I can run it and now I can see a grey bar at the top but nothing else. In the terminal i get this:
❯ ./bar
flutter: FormatException: Invalid number (at character 1)
flutter: 
flutter: ^
flutter: 
flutter: #0      int._handleFormatError (dart:core-patch/integers_patch.dart:124)
flutter: #1      int.parse (dart:core-patch/integers_patch.dart:50)
flutter: #2      MyBar.build (package:bar/bar.dart:17)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3846)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
flutter: #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5456)
flutter: #14     _InheritedProviderScopeElement.mount (package:provider/src/inherited_provider.dart:411)
flutter: #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4335)

It's stupid because the line that causes the FormatException is just blank. Any ideas?

**Comment by Ahmedazim7804** [comment]
you have all the folders in same path right?
also install [this package](https://github.com/wmww/gtk-layer-shell/) maybe your distro doesn't have it.
also can you tell what distro and hyprland version are you using?

**Comment by Manuelmik** [comment]
I have the bin <s>withhin</s> with the data/ and lib/ folder in the same place and the package gtk-layer-shell.
The issue still presists. My hyprland version is 0.42.0

**Comment by Ahmedazim7804** [comment]
`bar` has to be in the same folder as in `data` and `lib`.
```
├── bar
├── data
└── lib
```

**Comment by Manuelmik** [comment]
Sorry bad English. My folder structure is exactly the same as you explained.

**Comment by Ahmedazim7804** [comment]
Sorry for the late response.
I forgot to write in readme but you also need to put the config file in `~/.config/mybar/config.json`.

Here is the [example config file](https://raw.githubusercontent.com/Ahmedazim7804/flutter_bar_hyprland/refs/heads/master/config.json)

**Comment by Manuelmik** [comment]
thanks now the binary works. But i still cant compile it. Do i have to add the same JSON file somewhere in the folder structure of the flutter project?
